### NUMPY

In [2]:
import numpy as np
##create array using numpy
##creating a id array
arr1=np.array([1,2,3,4,5])
print(arr1,type(arr1))
print(arr1.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
(5,)


In [8]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [14]:
arr3=np.array([1,2,3,4,5])
arr3.reshape(1,5) ##1 row 5 column

array([[1, 2, 3, 4, 5]])

In [21]:
##@2d array
arr4=np.array([[1,2,3,4,5],[5,2,3,4,5]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [5 2 3 4 5]]
(2, 5)


In [24]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
## identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr=np.array([[1,2,3],[4,5,6]])
print("array:\n",arr)
print("shape:",arr.shape)
print("number of dimension:\t",arr.ndim)
print("size of the element:",arr.size)
print("data type:",arr.dtype)
print("item size:",arr.itemsize)

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimension:	 2
size of the element: 6
data type: int64
item size: 8


In [42]:
## vectorised operation of numpy
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
##element wise addition
print("addition\t",arr1+arr2)
##element wise subtarction
print("subtraction:\t",arr1-arr2)
##element wise multiplication
print("multiplication:",arr1*arr2)
##element wise division
print("division:\t",arr1/arr2)

addition	 [11 22 33 44 55]
subtraction:	 [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division:	 [0.1 0.1 0.1 0.1 0.1]


In [49]:
##universal funtion-->that applies to entire array
arr=np.array([2,3,4,5,6])
##sqrt
print(np.sqrt(arr))
##exponeatial
print(np.exp(arr))
##sine
print(np.sin(arr))
##cos
print(np.cos(arr))
##natural log
print(np.log(arr))
##log2
print(np.log2(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[1.         1.5849625  2.         2.32192809 2.5849625 ]


In [52]:
##slicing opeartion and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
arr[0][0]

np.int64(1)

In [62]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [73]:
arr[:2,0:2]

array([[1, 2],
       [5, 6]])

In [75]:
arr[:2,1:3]

array([[2, 3],
       [6, 7]])

In [78]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr[:2,2:]

array([[3, 4],
       [7, 8]])

In [80]:
arr[0:2][1:3]

array([[5, 6, 7, 8]])

In [87]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [109]:
## modify array element
arr[0,0]=100
print(arr)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [89]:
arr[1:]=100

In [106]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
###statical concepts-->normalization
## to change mean of 0 and standtsad deviation of 1
data=np.array([1,2,3,4,5])
##calcuate the mean and standrad deviation
mean=np.mean(data)
std_dev=np.std(data)
##normalise the data=
normalized_data=(data-mean)/std_dev
print("normalized data:",normalized_data)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [95]:
print(mean,std_dev)

3.0 1.4142135623730951


In [97]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
##mean
mean=np.mean(arr)
print("mean:",mean)
##median
median=np.median(arr)
print("median:",median)


##standrad dev
std_dev=np.std(arr)
print("Standrad dev:",std_dev)
##variance
variance=np.var(data)
print("variance:",variance)

mean: 5.5
median: 5.5
Standrad dev: 2.8722813232690143
variance: 2.0


In [105]:
## logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [110]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [129]:
arr[:2][2:3]

array([], shape=(0, 4), dtype=int64)

In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr)


array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr[1:2][:2]

array([[5, 6, 7, 8]])