### practicing numpy and pandas


In [2]:
!pip install numpy

In [3]:
import numpy as np
array_id=np.array([1,2,3,4,5,6])
print(array_id)

[1 2 3 4 5 6]


In [4]:
array_2dd=np.array([[1,2,3],[4,5,6]])
print(array_2dd)

[[1 2 3]
 [4 5 6]]


In [6]:
#element wise operation
array_sum=array_id+10
print(array_sum)

[11 12 13 14 15 16]


In [7]:
sqrt_array=np.sqrt(array_sum)
print(sqrt_array)

[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.        ]


In [8]:
!pip install pandas


In [9]:
import pandas as pd
series=pd.Series([1,2,3,4,5],index=["a","b","C","d","e"])
print(series)

a    1
b    2
C    3
d    4
e    5
dtype: int64


In [13]:
##create a data frame
data={
    "name":["barash","shivang","akshat"],
    "age":[25,30,35],
    "city":["goa","mumbai","delhi"]
}
df=pd.DataFrame(data)
print(df.loc[0])

name    barash
age         25
city       goa
Name: 0, dtype: object
